name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace with your branch name
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8

    - name: Build with Maven
      run: mvn clean install

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        docker-version: '20.10.7'  # Adjust the Docker version as needed

    # - name: Build Docker image
    #   run: |
    #     docker build -t ghcr.io/your-username/your-repo-name/your-image-name:latest .
    #     docker images

    # - name: Authenticate to GitHub Container Registry
    #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - name: Push Docker image to GitHub Container Registry
    #   run: |
    #     docker push ghcr.io/your-username/your-repo-name/your-image-name:latest

